# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GITHUB_REF_NAME
        run: echo $GITHUB_REF_NAME

      - name: make docker
        run: make docker
